config/routes.rb
Rails.application.routes.draw do

  resources :items

  root 'items#home'

end

app/models/catagory.rb
class Catagory < ActiveRecord::Base
  has_many :items
 
#  validates: presence

  def new
  end

  def all
  end



end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :items
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :category
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :course

  validates :item_name, :item_description, :item_price, presence: true

end

app/models/meal.rb
class Meal < ActiveRecord::Base
  has_many :items
  has_many :categories
end

app/models/mealtime.rb
class Mealtime < ActiveRecord::Base
  has_many :items
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :items
end

app/models/the_menu.rb
class TheMenu < ActiveRecord::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :show, :update, :destroy]
  # before_action :store_item, only: [:edit]

  def index
    @items = Item.all
  end

  def home
  end

  def new
    @item = Item.new
  end

  def show
  end

  def edit
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      redirect_to items_path, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end


  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end



  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :price, :description, :course_id)
    end

    # def store_item
    #   session[:item] = params[:id]
    # end

  end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/item/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
  <%= f.submit %>
</div>
  <% end %>

app/views/item/create.html.erb
<h1>Item#create</h1>
<p>Find me in app/views/item/create.html.erb</p>

app/views/item/edit.html.erb
<h1>Item#edit</h1>
<p>Find me in app/views/item/edit.html.erb</p>

app/views/item/index.html.erb
<h1>Item#index</h1>
<p>Find me in app/views/item/index.html.erb</p>

app/views/item/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', item_index_path %>

app/views/item/update.html.erb
<h1>Item#update</h1>
<p>Find me in app/views/item/update.html.erb</p>